export const experiments = [
  // {
  //   title: 'Painting By Numbers',
  //   imageUrl: 'http://dxlab.sl.nsw.gov.au/wp-content/uploads/2017/11/Screen-Shot-2017-11-13-at-2.10.05-pm.png',
  //   content: 'A digital experiment featuring nearly 300 original works by botanical artist Ferdinand Bauer',
  //   url: 'https://paintingbynumbers.dxlab.sl.nsw.gov.au',
  //   blogUrl: 'https://dxlab.sl.nsw.gov.au/painting-by-numbers',
  // },
  // {
  //   title: 'Meridian',
  //   imageUrl: 'http://dxlab.sl.nsw.gov.au/wp-content/uploads/2017/10/social-image.jpg',
  //   content: '17th and 18th century maps from the State Library of NSW’s collection brought to life as interactive 3D globes.',
  //   url: 'http://dxlab.sl.nsw.gov.au/meridian',
  //   blogUrl: 'http://dxlab.sl.nsw.gov.au/making-meridian',
  //   codeUrl: 'https://github.com/slnsw/dxlab-meridian',
  // },
  {
    title: 'Muru View',
    imageUrl: 'http://dxlab.sl.nsw.gov.au/wp-content/uploads/2017/06/MuruViewBanner4.jpg',
    content: 'Interactive data visualisation drawing from the Library\'s Indigenous language collections',
    url: 'http://dxlab.sl.nsw.gov.au/meridian',
    blogUrl: 'http://dxlab.sl.nsw.gov.au/making-meridian',
    codeUrl: 'https://github.com/slnsw/dxlab-meridian',
  },
  {
    title: 'Zooming Sydney',
    content: 'Interactive data visualisation drawing from the Library\'s Indigenous language collections',
    url: 'http://dxlab.sl.nsw.gov.au/meridian',
    imageUrl: 'http://dxlab.sl.nsw.gov.au/wp-content/uploads/2017/06/IMG_20170616_142738-1.jpg',
    blogUrl: 'http://dxlab.sl.nsw.gov.au/making-meridian',
  },
  {
    title: 'Loom',
    content: 'Interactive data visualisation drawing from the Library\'s Indigenous language collections',
    url: 'http://dxlab.sl.nsw.gov.au/meridian',
    imageUrl: 'http://dxlab.sl.nsw.gov.au/wp-content/uploads/2016/09/Screen-Shot-2016-09-16-at-3.21.37-pm.png',
    blogUrl: 'http://dxlab.sl.nsw.gov.au/making-meridian',
  },
  {
    title: 'Pano-scope',
    content: 'Interactive data visualisation drawing from the Library\'s Indigenous language collections',
    imageUrl: 'http://dxlab.sl.nsw.gov.au/wp-content/uploads/2017/06/IMG_20170616_142738-1.jpg',
    blogUrl: 'http://dxlab.sl.nsw.gov.au/making-meridian',
  },
];
